version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  keycloak:
      image: quay.io/keycloak/keycloak:19.0.3
      container_name: keycloak_image
      environment:
        KC_DB: postgres
        KC_DB_URL_HOST: pg_db
        KC_DB_URL_DATABASE: keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_SCHEMA: public
        KC_DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KEYCLOAK_IMPORT: /tmp/realm-export.json
      command: 
      - "start-dev"
      - "--import-realm"
      volumes:
      - ./export.json:/opt/keycloak/data/import/realm.json
      - ./keycloak-themes/keywind/theme/keywind/:/opt/keycloak/themes/keywind/
      ports:
        - 8180:8080
      networks:
      - keycloak_dev_network
  postgres_keycloak:
        image: postgres
        container_name: pg_db
        volumes:
          - pgdata_keycloak:/var/lib/postgres/data
        environment: 
          POSTGRES_DB: keycloak
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: password
        ports:
          - "5555:5432"
        networks:
          - keycloak_dev_network
volumes: 
  pgdata_keycloak:
  postgres_data:
    driver: local
networks:
  keycloak_dev_network:
    driver: bridge

          
