package tn.esprit.events.entities;

public enum NotificationType {
    STAFF_RECRUTMEMENT,STAFF_RECRUTMEMENT_RESPONSE,ORGANIZER_INVITE,ORGANIZER_INVITE_RESPONSE,PARTICIPANT_INVITE,
    PARTICIPANT_INVITE_RESPONSE,STAFF_DEMAND_REAUEST,STAFF_DEMAND_RESPONSE,REMINDER,PUB_REACTION,PUB_TAG,PUB_COMMENTS

}
